### PR TITLE
TVAULT-3969: Added firewall rules for dmapi ports

### PR DESCRIPTION
**Pull request by shyam-biradar**

### CODE REVIEW

**Comment by shyam-biradar** [comment]
@mwhahaha Please review

**Review by mwhahaha — APPROVED** [review]
Looks good to me

**Comment by shyam-biradar** [comment]
Tested on RHOSP16. Working fine.

**Comment by shyam-biradar** [comment]
> Looks good to me

Thank  you for the review @mwhahaha

**Pull request merged**
